/**
 * G4F Challenge Worker — Fast-Track Cake Credits
 *
 * A faster alternative to raw proof-of-work hashing: instead of grinding
 * SHA-256 nonces, the client solves small AI tasks (follow-up questions,
 * translations) generated by its LOCAL browser model (Chrome built-in
 * Gemini Nano via the Prompt API / LanguageModel).
 *
 * Flow:
 *   1. GET  /challenge/issue?lang=de-DE[&kind=followup|translation]
 *       → server issues an encrypted challenge (AES-GCM ciphertext of the
 *         task payload, sealed with a server-side key) plus a challenge id.
 *   2. The client decrypts the challenge in the browser, runs the prompt
 *       through its local LanguageModel, and POSTs the encrypted result to
 *       POST /challenge/solve { id, ciphertext, iv, language }.
 *   3. The server decrypts, validates the answer (JSON shape, language
 *       match, length, dedup), and mints a short-lived private-key JWT
 *       (HS256, signed with CHALLENGE_JWT_SECRET) that carries the credit.
 *   4. The JWT is exchanged for cakes: POST /challenge/redeem forwards the
 *       token to the cake worker's POST /cake/redeem, which re-verifies it
 *       and credits the shared ledger (CAKE_KV) — the user gets their first
 *       cakes without any hashing.
 *
 * Why encrypted challenges? The plaintext task never crosses the wire, so
 * the client must actually run its local model to produce an answer — the
 * ciphertext can't be matched against a lookup table, and the server-side
 * validation window (answer shape + language + freshness) keeps the bar low
 * enough for a small local model while still requiring real work.
 *
 * Endpoints:
 *   GET  /challenge/issue?lang=de-DE&kind=followup|translation|translations|any
 *        ("followups" is accepted as an alias for "followup")
 *   POST /challenge/solve      { id, ciphertext, iv, language }
 *   POST /challenge/redeem     { token }   — exchange JWT for cake credit
 *   GET  /challenge/translations?lang=de-DE   — community translations
 *   GET  /challenge/followups?lang=de-DE&count=3 — community follow-up questions
 *   GET  /challenge/status
 *   GET  /challenge/health
 *
 * Solved challenges feed the community stores directly in /challenge/solve:
 * "translations" answers merge into the translation store, "followup"
 * answers into the follow-ups pool (no separate submit endpoint).
 *
 * Storage (KV: CAKE_KV, shared with the cake worker):
 *   challenge:<id>          — sealed challenge record (TTL = CHALLENGE_TTL_SEC)
 *   challenge:seen:<hash>   — answer dedup (TTL = 1 day)
 *   challenge:rate:<ip>     — per-IP issue counter (TTL = 1 day)
 *   challenge:translations:<lang> — community translations per language
 *                                   ({"snippet": "translation"}, TTL = 1 year)
 *   challenge:followups:<lang>  — community follow-up questions per language
 *                                 ([{topic, q}], fed by solved followup
 *                                 challenges, TTL = 30 days)
 *   cakes:credit:<ip>       — the cake worker's credit ledger (credited here)
 *
 * Environment variables:
 *   CAKE_KV               — KV namespace binding (shared with cake-worker)
 *   CHALLENGE_SECRET      — AES-GCM key material (base64 or passphrase) for
 *                           sealing/unsealing challenges
 *   CHALLENGE_JWT_SECRET  — HMAC-SHA256 secret for signing the credit JWTs
 *   CAKE_CREDIT_CENTS     — credit per solved challenge (default: 5 = 0.05¢)
 *   CHALLENGE_PER_IP_PER_DAY — max solved challenges per IP/day (default: 100)
 *   CHALLENGE_TTL_SEC     — seconds before an issued challenge expires (default: 300)
 *   CHALLENGE_MAX_PER_DAY — max challenges issued per IP/day (default: 150)
 *   CAKE_WORKER_URL       — base URL of the cake worker that owns the ledger
 *                           and redeems tokens (default: https://g4f.space/cake)
 *   SNIPPETS_URL          — JSON file with UI snippets grouped by section
 *                           headline (context), e.g. /dist/js/snippets/chat.context.json.
 *                           Same-origin by default; must be fetchable from this worker.
 *   TRANSLATIONS_BATCH    — snippets per translations challenge (default: 8)
 *   ADMIN_API_KEY         — bearer token for admin endpoints
 */

const ALLOWED_ORIGINS = new Set([
    "https://g4f.dev",
    "https://g4f.space",
    "https://www.g4f.dev",
    "https://www.g4f.space",
    "http://localhost:8090",
    "http://localhost:8080",
    "http://127.0.0.1:8090",
    "http://127.0.0.1:8080",
]);

/** Build CORS headers for the request. Echoes the request Origin when allowed
 *  (or any localhost origin for dev) and enables credentials so the browser
 *  accepts the response when the client uses `credentials: "include"`. */
function corsHeaders(request) {
    const origin = request.headers.get("Origin") || "";
    const allowed =
        ALLOWED_ORIGINS.has(origin) ||
        /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(origin);
    return {
        "Access-Control-Allow-Origin": allowed ? origin : "null",
        "Access-Control-Allow-Credentials": "true",
        "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Forwarded-For, X-User",
        "Access-Control-Expose-Headers": "X-Cake-Credit",
        "Vary": "Origin",
    };
}

function json(body, status = 200, headers = {}, request) {
    return new Response(JSON.stringify(body), {
        status,
        headers: { "Content-Type": "application/json", ...corsHeaders(request), ...headers },
    });
}

/** Get the client IP from Cloudflare headers or the request. */
function getClientIP(request) {
    return (
        request.headers.get("CF-Connecting-IP") ||
        request.headers.get("X-Forwarded-For")?.split(",")[0]?.trim() ||
        request.headers.get("X-Real-IP") ||
        "0.0.0.0"
    );
}

/** Generate a v4 UUID without external deps. */
function uuidv4() {
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0"));
    return `${hex.slice(0, 4).join("")}-${hex.slice(4, 6).join("")}-${hex
        .slice(6, 8)
        .join("")}-${hex.slice(8, 10).join("")}-${hex.slice(10, 16).join("")}`;
}

function dayKey() {
    const d = new Date();
    return `${d.getUTCFullYear()}-${d.getUTCMonth() + 1}-${d.getUTCDate()}`;
}

function toBase64Url(buffer) {
    const bytes = new Uint8Array(buffer);
    let binary = "";
    for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
    return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function fromBase64Url(text) {
    const base64 = text.replace(/-/g, "+").replace(/_/g, "/");
    const padding = "=".repeat((4 - (base64.length % 4)) % 4);
    const binary = atob(base64 + padding);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
}

// ---------------------------------------------------------------------------
// Crypto: challenge sealing (AES-256-GCM) and JWT signing (HS256)
// ---------------------------------------------------------------------------

/** Derive the AES-GCM key from CHALLENGE_SECRET. Accepts raw base64 (32
 *  bytes) or any passphrase (hashed to 256 bits for a stable key). */
async function getSealKey(env) {
    const secret = env.CHALLENGE_SECRET || "g4f-challenge-dev-secret";
    let raw;
    try {
        const decoded = fromBase64Url(secret);
        if (decoded.length === 32) {
            raw = decoded;
        } else {
            raw = new TextEncoder().encode(secret);
        }
    } catch {
        raw = new TextEncoder().encode(secret);
    }
    const digest = await crypto.subtle.digest("SHA-256", raw);
    return crypto.subtle.importKey("raw", digest, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}

/** Seal a JSON payload into an AES-GCM ciphertext (base64url) + iv. */
async function sealPayload(env, payload) {
    const key = await getSealKey(env);
    const iv = crypto.getRandomValues(new Uint8Array(12));
    const plaintext = new TextEncoder().encode(JSON.stringify(payload));
    const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, plaintext);
    return { ciphertext: toBase64Url(ciphertext), iv: toBase64Url(iv) };
}

/** Unseal an AES-GCM ciphertext + iv back into a JSON payload (or null). */
async function unsealPayload(env, ciphertext, iv) {
    try {
        const key = await getSealKey(env);
        const plaintext = await crypto.subtle.decrypt(
            { name: "AES-GCM", iv: fromBase64Url(iv) },
            key,
            fromBase64Url(ciphertext)
        );
        return JSON.parse(new TextDecoder().decode(plaintext));
    } catch {
        return null;
    }
}

/** Sign a HS256 JWT carrying the given payload. Returns { token, expires }. */
async function signJwt(env, payload, ttlSec = 600) {
    const now = Math.floor(Date.now() / 1000);
    const fullPayload = { ...payload, iat: now, exp: now + ttlSec };
    const encode = (obj) => toBase64Url(new TextEncoder().encode(JSON.stringify(obj)));
    const unsignedToken = `${encode({ alg: "HS256", typ: "JWT" })}.${encode(fullPayload)}`;
    const key = await crypto.subtle.importKey(
        "raw",
        new TextEncoder().encode(env.CHALLENGE_JWT_SECRET || env.CHALLENGE_SECRET || "g4f-challenge-dev-secret"),
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"]
    );
    const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(unsignedToken));
    return { token: `${unsignedToken}.${toBase64Url(signature)}`, expires: fullPayload.exp };
}

/** Verify a HS256 JWT signed by signJwt. Returns the payload or null. */
async function verifyJwt(env, token) {
    try {
        const parts = token.split(".");
        if (parts.length !== 3) return null;
        const key = await crypto.subtle.importKey(
            "raw",
            new TextEncoder().encode(env.CHALLENGE_JWT_SECRET || env.CHALLENGE_SECRET || "g4f-challenge-dev-secret"),
            { name: "HMAC", hash: "SHA-256" },
            false,
            ["verify"]
        );
        const valid = await crypto.subtle.verify(
            "HMAC",
            key,
            fromBase64Url(parts[2]),
            new TextEncoder().encode(`${parts[0]}.${parts[1]}`)
        );
        if (!valid) return null;
        const payload = JSON.parse(new TextDecoder().decode(fromBase64Url(parts[1])));
        if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) return null;
        return payload;
    } catch {
        return null;
    }
}

// ---------------------------------------------------------------------------
// Challenge templates — follow-up questions & translations
// ---------------------------------------------------------------------------

/** Normalize a BCP-47 language tag to its base language ("de-DE" → "de"). */
function baseLanguage(tag) {
    return (tag || "en").split(/[-_]/)[0].toLowerCase();
}

/** Load the UI snippet catalogs: JSON files grouped by section headline
 *  ({ "<headline>": ["text", ...] }). The headline doubles as the
 *  translation context — "Send" means something else under "Message Input"
 *  than under "Legal & About". One catalog per page (chat, index, home,
 *  members, manifesto) is fetched and merged; groups starting with "_"
 *  are metadata and dropped. Cached in module scope (isolate lifetime). */
const SNIPPET_PAGES = [
    "chat",
    "index",
    "home",
    "members",
    "manifesto",
];
let snippetsCache = null;
let snippetsKeys = null;
async function loadSnippets(env) {
    if (snippetsCache) return snippetsCache;
    const base = env.SNIPPETS_URL || "/dist/js/snippets/chat.json";
    const urls = base.startsWith("http")
        ? [base]
        : SNIPPET_PAGES.map((path) => new URL(`/dist/js/snippets/${path}.json`, "https://g4f.dev").toString());
    const merged = {};
    for (const url of urls) {
        const res = await fetch(url, { cf: { cacheTtl: 3600, cacheEverything: true } });
        if (!res.ok) throw new Error(`snippets fetch failed: ${res.status} (${url})`);
        const catalog = await res.json();
        for (const [headline, texts] of Object.entries(catalog)) {
            if (headline.startsWith("_") || !Array.isArray(texts)) continue;
            // Headlines like "Navigation"/"Footer" exist in several catalogs;
            // merge without duplicates so batches never carry the same text
            // twice (the answer map is keyed by source text).
            const mergedTexts = merged[headline] || [];
            merged[headline] = [...new Set([...mergedTexts, ...texts])];
        }
    }
    snippetsCache = merged;
    snippetsKeys = [];
    Object.entries(merged).forEach(([headline, texts]) => {
        if (headline.startsWith("_") || !Array.isArray(texts)) return;
        snippetsKeys.push(headline);
        snippetsKeys.push(...texts);
    });
    return snippetsCache;
}

/** Build the challenge payload for a kind + language. The plaintext task is
 *  only ever sent sealed — the client decrypts it locally. */
function buildChallengePayload(kind, language) {
    const lang = baseLanguage(language);
    if (kind === "translation") {
        // A short English snippet the local model must translate.
        const snippets = [
            "The quick brown fox jumps over the lazy dog.",
            "A journey of a thousand miles begins with a single step.",
            "Practice makes perfect, but nobody is perfect.",
            "The weather today is sunny with a chance of rain.",
            "Actions speak louder than words.",
            "Better late than never, but never late is better.",
            "Every cloud has a silver lining.",
            "Knowledge is power, but enthusiasm pulls the switch.",
        ];
        const text = snippets[Math.floor(Math.random() * snippets.length)];
        return {
            kind: "translation",
            language: lang,
            prompt:
                `Translate the following text to ${language}. ` +
                `Return as JSON: {"text": "<translation>"}`,
            text,
        };
    }
    if (kind === "translations") {
        // Batch mode: translate real UI snippets (filled in by handleIssue,
        // which can await loadSnippets) — the result feeds the community
        // translation store served back to the chat UI.
        return { kind: "translations", language: lang, items: [] };
    }
    // Default: follow-up questions (same shape the chat UI generates).
    const topics = [
        "a weekend project idea",
        "an interesting historical event",
        "a healthy breakfast",
        "a good book to read",
        "a beginner-friendly hobby",
        "a way to stay focused while working",
        "a place worth traveling to",
        "a small daily habit that improves life",
    ];
    const topic = topics[Math.floor(Math.random() * topics.length)];
    return {
        kind: "followup",
        language: lang,
        prompt:
            `Suggest 3 short follow-up questions about ${topic}. ` +
            `Use first-person language. Return as JSON: {"q": ["...", "...", "..."]}\n` +
            `Response in language \`${language}\` (iso-code)`,
        topic,
    };
}

/** Validate a decrypted answer against its challenge payload. Returns an
 *  error string or null when the answer is acceptable. */
function validateAnswer(payload, answer, language) {
    if (!answer || typeof answer !== "object") return "answer_not_json";
    if (payload.kind === "translations") {
        // Batch: expect { translations: { "<source>": "<translation>" } }.
        const translations = answer.translations || answer;
        if (!translations || typeof translations !== "object" || Array.isArray(translations)) {
            return "missing_translations";
        }
        const sources = Object.keys(translations);
        const knownKeys = sources.filter((key) => snippetsKeys.includes(key));
        if (sources.length === 0 || knownKeys.length === 0) return "missing_translations";
        if (sources.length > 100 || knownKeys.length > 100) return "too_many_translations";
        if (!("..." in translations)) return "invalid_translation";
        for (const translated of Object.values(translations)) {
            if (typeof translated !== "string") return "invalid_translation";
            if (translated.length > 2000) return "invalid_translation";
            if (!translated.trim()) return "not_translated";
        }
        return null;
    }
    if (payload.kind === "translation") {
        const text = answer.text;
        if (typeof text !== "string" || !text.trim()) return "missing_text";
        if (text.length < 5 || text.length > 2000) return "text_length";
        // The translation must differ from the English source.
        if (text.trim().toLowerCase() === payload.text.trim().toLowerCase()) return "not_translated";
        return null;
    }
    // followup: expect a non-empty "q" array (or "questions") of strings.
    const questions = answer.q || answer.questions || answer;
    if (!Array.isArray(questions) || questions.length < 2) return "missing_questions";
    if (questions.length > 8) return "too_many_questions";
    for (const q of questions) {
        if (typeof q !== "string" || q.trim().length < 3) return "invalid_question";
        if (q.length > 500) return "invalid_question";
    }
    return null;
}

/** Stable hash of the answer for dedup (same answer shouldn't double-credit). */
async function answerHash(ip, payload, answer) {
    const data = new TextEncoder().encode(
        JSON.stringify({ ip, kind: payload.kind, text: payload.text || payload.topic, answer })
    );
    const digest = await crypto.subtle.digest("SHA-256", data);
    return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ---------------------------------------------------------------------------
// Community follow-ups pool
// ---------------------------------------------------------------------------

const FOLLOWUPS_MAX_TOPICS = 100;

/** Add a solved question set to the per-language follow-ups pool. The pool
 *  is what GET /challenge/followups serves to the chat UI, so solved
 *  challenges become free suggestions for everyone. Best-effort: callers
 *  wrap this in try/catch. */
async function addFollowups(env, language, topic, questions) {
    const lang = baseLanguage(language);
    const clean = (questions || [])
        .filter((q) => typeof q === "string" && q.trim().length >= 3 && q.trim().length <= 500)
        .map((q) => q.trim());
    if (!lang || clean.length < 2) return;
    const storeKey = `challenge:followups:${lang}`;
    const raw = await env.CAKE_KV.get(storeKey);
    let pool = [];
    try { pool = raw ? JSON.parse(raw) : []; } catch { pool = []; }
    // Skip exact duplicates (the solve dedup only blocks them for a day).
    const fingerprint = clean.join("|").toLowerCase();
    if (pool.some((entry) => (entry.q || []).join("|").toLowerCase() === fingerprint)) return;
    // One entry per topic (a re-solved topic refreshes its questions).
    const filtered = pool.filter((entry) => entry.topic !== topic);
    filtered.push({ topic: topic || "general", q: clean, at: Date.now() });
    while (filtered.length > FOLLOWUPS_MAX_TOPICS) {
        filtered.shift(); // drop the oldest entries
    }
    await env.CAKE_KV.put(storeKey, JSON.stringify(filtered), { expirationTtl: 86400 * 30 });
}

// ---------------------------------------------------------------------------
// KV helpers
// ---------------------------------------------------------------------------

async function getIssuedCount(env, ip) {
    const raw = await env.CAKE_KV.get(`challenge:rate:${ip}`);
    if (!raw) return 0;
    try {
        const parsed = JSON.parse(raw);
        return parsed.day === dayKey() ? parsed.count : 0;
    } catch {
        return 0;
    }
}

async function incrementIssuedCount(env, ip) {
    const count = (await getIssuedCount(env, ip)) + 1;
    await env.CAKE_KV.put(`challenge:rate:${ip}`, JSON.stringify({ count, day: dayKey() }), {
        expirationTtl: 86400,
    });
    return count;
}

// ---------------------------------------------------------------------------
// Route handlers
// ---------------------------------------------------------------------------

/** GET /challenge/issue?lang=de-DE&kind=followup|translation|any
 *  "any" falls back to a followup when no translations are pending. */
async function handleIssue(request, env) {
    const ip = getClientIP(request);
    const url = new URL(request.url);
    const maxPerDay = Number(env.CHALLENGE_MAX_PER_DAY || 150);
    const ttlSec = Number(env.CHALLENGE_TTL_SEC || 300);

    const issued = await getIssuedCount(env, ip);
    if (issued >= maxPerDay) {
        return json(
            { error: "daily_limit_reached", issued_today: issued, limit: maxPerDay },
            429,
            { "Retry-After": "3600" },
            request
        );
    }

    const kindParam = (url.searchParams.get("kind") || "any").toLowerCase();
    // "followups" is accepted as an alias for "followup".
    const explicitKind = ["followup", "followups", "translation", "translations"].includes(kindParam);
    let kind = explicitKind
        ? (kindParam === "followups" ? "followup" : kindParam)
        : Math.random() < 0.2
            ? "followup"
            : "translations";
    const language = url.searchParams.get("lang") || "en";

    let payload = buildChallengePayload(kind, language);
    if (kind === "translations") {
        // Fill the batch with real UI snippets; the section headline is the
        // translation context. Snippets that already have a community
        // translation for this language are skipped.
        let snippets;
        try {
            snippets = await loadSnippets(env);
        } catch (err) {
            return json({ error: "snippets_unavailable", message: String(err) }, 503, {}, request);
        }
        const existingRaw = await env.CAKE_KV.get(`challenge:translations:${baseLanguage(language)}`);
        let existing = {};
        try { existing = existingRaw ? JSON.parse(existingRaw) : {}; } catch { /* fresh store */ }
        const batch = Math.min(Math.max(Number(env.TRANSLATIONS_BATCH) || 8, 2), 50);
        const candidates = [];
        for (const [headline, texts] of Object.entries(snippets)) {
            if (headline.startsWith("_") || !Array.isArray(texts)) continue;
            const untranslated = texts.filter((s) => !existing[s]);
            if (untranslated.length === 0) continue;
            candidates.push([headline, untranslated]);
        }
        if (candidates.length === 0) {
            // Nothing left to translate for this language. An explicit
            // translations request reports it; a generic "any" request falls
            // back to a followup challenge so the client still gets work.
            if (explicitKind) {
                return json({ error: "all_translated", language }, 200, {}, request);
            }
            kind = "followup";
            payload = buildChallengePayload(kind, language);
        }
        if (payload.kind === "translations") {
            // Pick among the groups with the most untranslated texts (weighted,
            // not deterministic) — a single stubborn group must not keep serving
            // the identical challenge while other groups wait. Capped at
            // TRANSLATIONS_BATCH texts per challenge.
            candidates.sort((a, b) => b[1].length - a[1].length);
            const top = candidates.slice(0, Math.min(3, candidates.length));
            const [headline, untranslated] = top[Math.floor(Math.random() * top.length)];
            const pending = [headline, ...untranslated.slice(0, batch), "..."];
            payload.items = pending;
            payload.prompt =
                `Translate these UI texts to language \`${language}\` (iso-code). ` +
                `Keep placeholders like {0} intact. Return as JSON: ` +
                `{"translations": {"<source text>": "<translation>"}}\n` +
                `${JSON.stringify({ items: Object.fromEntries(pending.map((item) => [item, ""])) }, null, 2)}`;
        }
    }

    const { ciphertext, iv } = await sealPayload(env, payload);
    const id = uuidv4();

    await env.CAKE_KV.put(
        `challenge:${id}`,
        JSON.stringify({ ip, kind: payload.kind, language: payload.language, topic: payload.topic, issued_at: Date.now() }),
        { expirationTtl: ttlSec }
    );
    await incrementIssuedCount(env, ip);

    return json({
        id,
        ciphertext,
        iv,
        algorithm: "AES-GCM",
        // The seal secret, published to the client. The challenge encryption
        // is obfuscation against casual scrapers, not secrecy: the secret is
        // by design also available in the page bundle, and the real gate is
        // server-side answer validation. Deployments that embed the secret
        // in the page and want to withhold it can strip this field.
        keySalt: env.CHALLENGE_SECRET || "g4f-challenge-dev-secret",
        kind, // hint only — the sealed payload is authoritative
        language: payload.language,
        ttl: ttlSec,
        credit_cents: Number(env.CAKE_CREDIT_CENTS || 5),
    }, 200, {}, request);
}

/** POST /challenge/solve { id, ciphertext, iv, language } */
async function handleSolve(request, env) {
    const ip = getClientIP(request);
    const perDay = Number(env.CHALLENGE_PER_IP_PER_DAY || 100);
    const creditCents = Number(env.CAKE_CREDIT_CENTS || 5);

    let body;
    try {
        body = await request.json();
    } catch {
        return json({ error: "invalid_json" }, 400, {}, request);
    }
    const { id, ciphertext, iv, language } = body;
    if (!id || !ciphertext || !iv) {
        return json({ error: "missing_fields", required: ["id", "ciphertext", "iv"] }, 400, {}, request);
    }
    if (typeof id !== "string" || id.length > 64 || typeof ciphertext !== "string" || typeof iv !== "string") {
        return json({ error: "invalid_field_types" }, 400, {}, request);
    }
    if (ciphertext.length > 16384 || iv.length > 64) {
        return json({ error: "invalid_field_lengths" }, 400, {}, request);
    }

    // 1. The challenge must exist, be unexpired and belong to this IP.
    const recordRaw = await env.CAKE_KV.get(`challenge:${id}`);
    if (!recordRaw) {
        return json({ error: "challenge_not_found_or_expired" }, 403, {}, request);
    }
    let record;
    try {
        record = JSON.parse(recordRaw);
    } catch {
        return json({ error: "challenge_corrupted" }, 500, {}, request);
    }
    if (record.ip !== ip) {
        return json({ error: "challenge_not_issued_to_ip", ip }, 403, {}, request);
    }

    // 2. Unseal the client's encrypted answer.
    const answer = await unsealPayload(env, ciphertext, iv);
    if (!answer) {
        return json({ error: "decrypt_failed" }, 400, {}, request);
    }

    // 3. Rebuild the expected payload deterministically? No — the sealed
    //    payload was random at issue time, so instead validate the answer
    //    against the challenge kind + language recorded at issue time.
    const payload = buildChallengePayload(record.kind, record.language);
    const error = validateAnswer(payload, answer, language || record.language);
    if (error) {
        return json({ error, kind: record.kind }, 400, {}, request);
    }

    // 5. Enforce the daily solve limit.
    const solvedRaw = await env.CAKE_KV.get(`challenge:solved:${ip}`);
    let solved = { count: 0, day: dayKey() };
    if (solvedRaw) {
        try {
            const parsed = JSON.parse(solvedRaw);
            if (parsed.day === dayKey()) solved = parsed;
        } catch { /* fresh counter */ }
    }
    if (solved.count >= perDay) {
        return json({ error: "daily_limit_reached", limit: perDay }, 429, { "Retry-After": "3600" }, request);
    }
    await env.CAKE_KV.put(
        `challenge:solved:${ip}`,
        JSON.stringify({ count: solved.count + 1, day: dayKey() }),
        { expirationTtl: 86400 }
    );

    // 6. Burn the challenge so it can't be solved twice.
    await env.CAKE_KV.delete(`challenge:${id}`);

    // 6b. Feed the community follow-ups pool: a solved question set becomes
    //     a suggestion the chat UI can serve to every visitor for free.
    if (record.kind === "followup" && Array.isArray(answer.q)) {
        try {
            await addFollowups(env, record.language, record.topic, answer.q);
        } catch { /* pool is best-effort */ }
    }

    if (record.kind === "translations") {
        try {
            await handleTranslationsSubmit(record.language, answer, env);
        } catch { /* pool is best-effort */ }
    }

    // 7. Dedup: the exact same answer may only be credited once per day.
    //    Checked before burning/crediting so a duplicate wastes neither the
    //    challenge nor a daily solve slot — its translations were already
    //    persisted on the first submission, and the client treats this
    //    response as "round complete".
    const dedupKey = `challenge:seen:${await answerHash(ip, payload, answer)}`;
    if (await env.CAKE_KV.get(dedupKey)) {
        return json({ error: "duplicate_answer" }, 409, {}, request);
    }
    await env.CAKE_KV.put(dedupKey, "1", { expirationTtl: 86400 });

    // 7. Mint the private-key JWT carrying the credit claim.
    const { token, expires } = await signJwt(
        env,
        {
            sub: `challenge:${ip}`,
            kind: record.kind,
            language: record.language,
            credit_cents: creditCents,
            challenge_id: id,
        },
        600
    );

    return json({
        ok: true,
        token,
        expires,
        credit: creditCents,
        credit_cents: creditCents,
        solved_today: solved.count + 1,
        limit_per_day: perDay,
    }, 200, {}, request);
}

/** POST /challenge/redeem { token } — exchange a solve-JWT for cake credit.
 *  Redemption lives on the cake worker (the ledger owner): the token is
 *  forwarded to POST /cake/redeem, which re-verifies it, replay-marks it and
 *  credits cakes:credit:<ip> via the cake worker's own addCredit (so challenge
 *  earnings also show up in /cake/users). */
async function handleRedeem(request, env) {
    const ip = getClientIP(request);

    let body;
    try {
        body = await request.json();
    } catch {
        return json({ error: "invalid_json" }, 400, {}, request);
    }
    const token = body.token || (request.headers.get("Authorization") || "").replace(/^Bearer\s+/i, "");
    if (!token) {
        return json({ error: "missing_token" }, 400, {}, request);
    }

    // Verify locally first — fast rejection of garbage/tampered/foreign-IP
    // tokens without a round-trip to the cake worker.
    const payload = await verifyJwt(env, token);
    if (!payload) {
        return json({ error: "invalid_or_expired_token" }, 401, {}, request);
    }
    if (payload.sub !== `challenge:${ip}`) {
        return json({ error: "token_bound_to_other_ip" }, 403, {}, request);
    }
    if ((Number(payload.credit_cents) || 0) <= 0) {
        return json({ error: "no_credit" }, 400, {}, request);
    }

    // Local replay pre-check. The marker is written by the cake worker into
    // the SHARED CAKE_KV using the same hash, so this saves the upstream call
    // on double redemptions. Its TTL (900s) outlives the token TTL (600s),
    // after which verifyJwt rejects the token anyway.
    const redeemedKey = `challenge:redeemed:${await answerHash(ip, { kind: "redeem" }, { jti: payload.challenge_id })}`;
    if (await env.CAKE_KV.get(redeemedKey)) {
        return json({ error: "token_already_redeemed" }, 409, {}, request);
    }

    // Forward to the cake worker — the ledger owner. It re-verifies the JWT
    // and credits the IP embedded in the token (payload.sub), so the proxy's
    // egress IP does not affect attribution.
    const base = (env.CAKE_WORKER_URL || "https://g4f.space/cake").replace(/\/+$/, "");
    let upstream;
    try {
        upstream = await fetch(`${base}/redeem`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Origin": request.headers.get("Origin") || "",
                "X-User": request.headers.get("X-User") || "",
                "X-Forwarded-For": ip,
            },
            body: JSON.stringify({ token }),
        });
    } catch (err) {
        return json({ error: "cake_worker_unreachable", message: String(err) }, 502, {}, request);
    }
    const data = await upstream.json().catch(() => ({}));
    if (!upstream.ok) {
        return json(
            data && data.error ? data : { error: "redeem_failed", upstream_status: upstream.status },
            upstream.status,
            {},
            request
        );
    }
    return json(data, upstream.status, {}, request);
}

/** Merge solved "translations" answers into the per-language community
 *  store. Internal helper called from handleSolve (the solve JWT already
 *  credits the user — no separate token check here). Throws on invalid
 *  input; the caller treats the pool as best-effort. */
async function handleTranslationsSubmit(language, translations, env) {
    translations = translations.translations || translations;
    language = baseLanguage(language || "");
    if (!language || language === "en") {
        throw new Error("invalid_language");
    }
    const entries = Object.entries(translations).filter(
        ([source, translated]) =>
            typeof source === "string" && source.trim() &&
            typeof translated === "string" && translated.trim()
        // Identity translations (translation === source) are kept: proper
        // nouns and brand names ("Cloud (g4f.space)", "GitHub") legitimately
        // translate to themselves, and rejecting them would leave their
        // group permanently untranslated — re-serving the same challenge.
    );
    const knownTranslations = entries.filter(([source, _]) => snippetsKeys.includes(source));
    if (entries.length === 0 || knownTranslations.length === 0) {
        throw new Error("no_valid_translations");
    }
    if (entries.length > 100 || knownTranslations.length > 100) {
        throw new Error("too_many_translations");
    }

    // Merge into the per-language community store.
    const storeKey = `challenge:translations:${language}`;
    const raw = await env.CAKE_KV.get(storeKey);
    let store = {};
    try { store = raw ? JSON.parse(raw) : {}; } catch { /* fresh store */ }
    let added = 0;
    for (const [source, translated] of knownTranslations) {
        if (!store[source]) added += 1;
        store[source] = translated.trim();
    }
    await env.CAKE_KV.put(storeKey, JSON.stringify(store), { expirationTtl: 86400 * 365 });

    return { ok: true, language, added, total: Object.keys(store).length };
}

/** GET /challenge/translations?lang=de-DE — community translations for the
 *  chat UI's translateAll() to reuse instead of re-translating everything. */
async function handleTranslationsGet(request, env) {
    const url = new URL(request.url);
    const language = baseLanguage(url.searchParams.get("lang") || "");
    if (!language || language === "en") {
        return json({ error: "invalid_language" }, 400, {}, request);
    }
    const raw = await env.CAKE_KV.get(`challenge:translations:${language}`);
    let translations = {};
    try { translations = raw ? JSON.parse(raw) : {}; } catch { /* fresh store */ }
    return json(
        { language, count: Object.keys(translations).length, translations },
        200,
        { "Cache-Control": "public, max-age=300" },
        request
    );
}

/** GET /challenge/followups?lang=de-DE&count=3 — community follow-up
 *  questions for the chat UI's suggestion chips, fed by solved followup
 *  challenges. Same response shape as the model-generated suggestions
 *  ({q: [...]}), so the UI can use it as a free first try. */
async function handleFollowupsGet(request, env) {
    const url = new URL(request.url);
    const language = baseLanguage(url.searchParams.get("lang") || "en");
    const count = Math.min(Math.max(Number(url.searchParams.get("count")) || 3, 1), 8);
    const raw = await env.CAKE_KV.get(`challenge:followups:${language}`);
    let pool = [];
    try { pool = raw ? JSON.parse(raw) : []; } catch { pool = []; }
    if (pool.length === 0) {
        return json({ error: "no_followups", language }, 404, {}, request);
    }
    // Random topic, shuffled questions — repeat visits see variety.
    const entry = pool[Math.floor(Math.random() * pool.length)];
    const shuffled = entry.q.slice();
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return json(
        { ok: true, language, topic: entry.topic, q: shuffled.slice(0, count) },
        200,
        { "Cache-Control": "public, max-age=60" },
        request
    );
}

/** GET /challenge/status — current IP's challenge stats. */
async function handleStatus(request, env) {
    const ip = getClientIP(request);
    const solvedRaw = await env.CAKE_KV.get(`challenge:solved:${ip}`);
    let solved = { count: 0, day: dayKey() };
    if (solvedRaw) {
        try {
            const parsed = JSON.parse(solvedRaw);
            if (parsed.day === dayKey()) solved = parsed;
        } catch { /* fresh counter */ }
    }
    const creditRaw = await env.CAKE_KV.get(`cakes:credit:${ip}`);
    const credit = creditRaw ? Number(creditRaw) || 0 : 0;
    return json({
        ip,
        solved_today: solved.count,
        limit_per_day: Number(env.CHALLENGE_PER_IP_PER_DAY || 100),
        credit_cents: credit,
        credit_usd: (credit / 100).toFixed(4),
    }, 200, {}, request);
}

// ---------------------------------------------------------------------------
// Entrypoint
// ---------------------------------------------------------------------------

export default {
    async fetch(request, env, ctx) {
        const url = new URL(request.url);
        const pathname = url.pathname;

        if (request.method === "OPTIONS") {
            return new Response(null, { headers: corsHeaders(request) });
        }

        if (pathname === "/challenge/health") {
            return json({
                ok: true,
                service: "challenge-worker",
                kv: Boolean(env.CAKE_KV),
                kv_source: env.CHALLENGE_KV_SOURCE || null,
            }, 200, {}, request);
        }

        // Degrade gracefully when the KV binding is missing (e.g. the Upstash
        // env vars are not configured on a deployment) — a clear 503 beats a
        // crashed function (FUNCTION_INVOCATION_FAILED).
        if (!env.CAKE_KV || typeof env.CAKE_KV.get !== "function") {
            return json(
                { error: "kv_unavailable", message: "CAKE_KV binding is not configured on this deployment." },
                503,
                {},
                request
            );
        }

        try {
            if (pathname === "/challenge/issue" && request.method === "GET") {
                return await handleIssue(request, env);
            }
            if (pathname === "/challenge/solve" && request.method === "POST") {
                return await handleSolve(request, env);
            }
            if (pathname === "/challenge/redeem" && request.method === "POST") {
                return await handleRedeem(request, env);
            }
            if (pathname === "/challenge/translations" && request.method === "GET") {
                return await handleTranslationsGet(request, env);
            }
            if (pathname === "/challenge/followups" && request.method === "GET") {
                return await handleFollowupsGet(request, env);
            }
            if (pathname === "/challenge/status" && request.method === "GET") {
                return await handleStatus(request, env);
            }
            if (pathname === "/challenge/health") {
                return json({ ok: true, service: "challenge-worker" }, 200, {}, request);
            }
            return json(
                { error: "not_found", endpoints: ["/challenge/issue", "/challenge/solve", "/challenge/redeem", "/challenge/translations", "/challenge/followups", "/challenge/status"] },
                404,
                {},
                request
            );
        } catch (err) {
            return json({ error: "internal", message: String(err) }, 500, {}, request);
        }
    },
};
